### ISSUE TITLE
Question about Phase 1 training

### ISSUE THREAD

**Issue by skleee** [HansiZeng/RIPOR#1]
Hi, thanks for your great work and sharing your code!

I'm trying to reproduce RIPOR from phase 1 (relevance-based docid initialization) to get $M^0$. 

Based on the two-stage strategy, it seems that the model is trained using MarginMSE loss with BM25 negative in the initial stage, and then **the nearest neighbor search** is needed for training the model with MarginMSE loss for the second stage.

Here, I wonder which code should be used to run the nearest neighbor search for the second stage. When I run `full_scripts/full_train_t5seq_encoder_1.sh` as written in README.md after the first stage, I get the following error. 

```
FileNotFoundError: [Errno 2] No such file or directory: './experiments-full-t5seq-aq/t5_docid_gen_encoder_0/all_train/MSMARCO_TRAIN/qrel_added_qid_docids_teacher_scores.train.json
```

Would you please tell me what code to run to get the `qrel_added_qid_docids_teacher_scores.train.json` from model $M$ which is trained with BM25 negatives?

Thank you in advance :)

**Comment by HansiZeng** [comment]
Hi Sunkyung, 
Thanks for your interest in my work.
**Bad News**:  This work was done when I was an intern at Amazon. I forgot to upload the `t5_docid_gen_encoder_0` to my Google Drive, and now I cannot access it.
**Good News**: I think we can obtain the `qrel_added_qid_docids_teacher_scores.train.json` by ourself based on the code and model $M^0$ we have. The following are the step-by-step instructions to obtain this file.
Step 1: Index the whole collection by $M^0$. 
- First, You should change the `task` variable in line 3 of `full_scripts/full_evaluate_t5seq_aq_encoder.sh` to `task=all_pipline`.  
- Next, Assume your $M^0$ is named as `t5_docid_gen_encoder_0`, you also need to set `model_dir="./$experiment_dir/t5_docid_gen_encoder_0` in line 92 of the same file. 
- Finally, you run the script: `full_scripts/full_evaluate_t5seq_aq_encoder.sh`.  After running the script, the index should locate in `$model_dir/index`, and my code also outputs the performance of $M^0$ on MSMARCO Dev, TREC-DL 19, and TREC-DL 20 respectively. 

Step 2: retrieve the top 100 documents for each trained query by the model $M^0$.
- First, You should change the `task` variable in line 3 of `full_scripts/full_evaluate_t5seq_aq_encoder.sh` to `task=retrieve_train_queries`.
- Second,   set `model_dir="./$experiment_dir/t5_docid_gen_encoder_0"` in line 76 of the same file.
- Third,  run the script `full_scripts/full_evaluate_t5seq_aq_encoder.sh`. Then you should see new `run.json` file is created and located at `$model_dir/out/MSMARCO_TRAIN/run.json`

Step 3: give each query-document pair in the run.json a teacher score. 
- Go the the script `full_scripts/rerank_for_create_trainset.sh` and set `run_path=$root_dir/t5_docid_gen_encoder_0/out/MSMARCO_TRAIN/run.json` in line 9 and `out_dir=$root_dir/t5_docid_gen_encoder_0/out/MSMARCO_TRAIN/` in line 10,
- Then run the script: `full_scripts/rerank_for_create_trainset.sh`
- You should see a new file is created and located in `$model_dir/out/MSMARCO_TRAIN/qid_docids_teacher_scores.train.json`

Step 4: Since not all top 100 docids for each query contain the relevant docids, we should add these relevant docids back if they are not in top 100 list. 
- First, go the  python file: `t5_pretrainer/aq_preprocess/add_qrel_to_rerank_run.py` and assign the variable `qid_pids_rerank_scores_path` in line 7 to the path `$model_dir/out/MSMARCO_TRAIN/qid_docids_teacher_scores.train.json`. And change the `out_path`in  line 9 to the path `$model_dir/out/MSMARCO_TRAIN/qrel_added_qid_docids_teacher_scores.train.json`. 
- Run the file `t5_pretrainer/aq_preprocess/add_qrel_to_rerank_run.py`. Then you can get the `qrel_added_qid_docids_teacher_scores.train.json` you want. 


It is a little complicated, and if you face any bug in any step, don't hesitate to contact me, then I can help you out.

**Comment by skleee** [comment]
Thank you very much for your quick reply.
I will try to follow your instructions :)
