### ISSUE TITLE
Missing Class PrefixConstrainLogitProcessorFastSparseMultiShape in Phase 3 

### ISSUE THREAD

**Issue by eitanOr** [HansiZeng/RIPOR#4]
Thank you for sharing your code and for all the hard work that went into it! 

I encountered an issue while executing the script `full_scripts/full_evaluate_t5seq_aq_encoder.sh` configured with `task=t5seq_aq_get_qid_to_smtid_rankdata`. 

It appears that the class `PrefixConstrainLogitProcessorFastSparseMultiShape` is missing during the execution of the function `t5seq_aq_get_qid_to_smtid_rankdata` in the Phase 3.

This missing class prevents the script from completing as expected. Could you please check this and possibly update the repository with the necessary class?

Thank you!

**Comment by HansiZeng** [comment]
Hi,
Thanks for your interest in the work! 
Since the model's vocabulary size at each step is the same, `len(set(model.config.decoder_vocab_sizes)) == 1` is always true, hence the `PrefixConstrainLogitProcessorFastSparseMultiShape` will never be called. In case you face the compiler related issues, I comment out the unused code. Please check the new version.

Additionally, the program requires quite large memory, if you don't have enough memory, the program might be terminated. For your reference, I use the Slurm to run the job. The following is my sbatch script. As you see, I request 240G memory when I use 1 GPU: 
```
#!/bin/bash
export CUDA_VISIBLE_DEVICES=0
sbatch --job-name=${base_name} --output=sbatch_jobs/sbatch_out/run_script_1.out \
        -p hgx-alpha -G 1 --nodes=1 --cpus-per-task=32 --mem=240G --time=7-00:00:00 \
        --wrap=". /work/hzeng_umass_edu/miniconda3/etc/profile.d/conda.sh && conda activate ripor && bash full_scripts/full_evaluate_t5seq_aq_encoder.sh"
```
If you request more GPUs, you need more memory. 

If you still face the problem, please don't hesitate to contact me.
